### ISSUE TITLE
No automatic default info filling when OA instance is opened

### ISSUE THREAD

**Issue by mdsina** [odin-public/RESTED-APS#12]
In RestClient-APS there are a great stuff when you already have opened OA instance and the default URLs to API and aps/2/resources auto-filled.

**Comment by gear54rus** [comment]
It is a planned feature with no ETA. This project aims for feature parity with original RESTClient-APS so don't worry.

**Comment by gear54rus** [comment]
Needs #16.

**Comment by gear54rus** [comment]
This needs a content script to pull things from pages. And it should not degrade performance. Use this: https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback
