### ISSUE TITLE
Add the ability to be pre-configured using URLs

### ISSUE THREAD

**Issue by gear54rus** [odin-public/RESTED-APS#16]
**Do you want to request a *feature* or report a *bug*?**  
Feature

**Your envieronment**
Any

**What is the current behavior?**
Currently it is not possible to pre-configure new RESTED APS window by supplying data in the URL.

**What is the expected behavior?**
We will be able to pass data in URL (URL fragment seems to be the most suited) and the newly opened window will have some things pre-filled.

This can be used for URLs, APS Tokens and more.

**Videos/screenshots of the issue**
N/A

**Comment by gear54rus** [comment]
This needs a content script to pull things from pages. And it should not degrade performance. Use this: https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback

**Comment by gear54rus** [comment]
It seems to be useless for upstream, maybe @esphen can say otherwise. Closed for now.

**Comment by eliihen** [comment]
Hey Paul!

I guess this is related to a couple of issues I've gotten: https://github.com/RESTEDClient/RESTED/issues/109 and https://github.com/RESTEDClient/RESTED/issues/35. I started working on https://github.com/RESTEDClient/RESTED/issues/35, but I don't think I pushed that branch yet.

My implementation works via URLs with a search like `?action=importHar&data=...`. That seems more flexible, if you ask me.

**Comment by gear54rus** [comment]
@esphen forked into #19.
