### ISSUE TITLE
Auto-complete OA API URL

### ISSUE THREAD

**Issue by burashka** [odin-public/RESTED-APS#21]
**Do you want to request a *feature* or report a *bug*?**  
feature (but regression from old version)

**Your envieronment**
FF

**What is the current behavior?**
Need manual entry OA API URL

**What is the expected behavior?**
Auto-complete after entry URL

**Comment by gear54rus** [comment]
@burashka 

How do you see this scenario? What if user entered custom OA API URL (e.g. API is accessible over IP and APS API is accessible over hostname) and then changed the main URL? What criteria should I use to know when to change the OA API URL?

**Comment by burashka** [comment]
Propose variant: one way binding. Change hostname - change API URL. Change API URL - doesn't change URL

**Comment by gear54rus** [comment]
Fixed in 7294a88
