### ISSUE TITLE
Bug in functionality that obtains the APS Token for a User, based on the User ID

### ISSUE THREAD

**Issue by AngelDevel** [odin-public/RESTED-APS#45]
**Do you want to request a *feature* or report a *bug*?**  
Report a bug

**Your envieronment**
Win, Chrome, extension RESTED APS 0.0.7

**What is the current behavior?**
The Authentication Type : APS Token > based on User, doesn't seem to be working correctly. 
When I try to obtain the APS Token for a specific user, providing the User ID, the extension returns the following message: "An error occurred while refreshing the token: OA API error: java.lang.NullPointerException: null"

**What is the expected behavior?**
I would expect to obtain the APS Token for that User ID

**Videos/screenshots of the issue**

**Possible Cause**
A typo in the current code. Looking at the code in https://github.com/odin-public/RESTED-APS/blob/next/src/utils/aps.js, it seems that:

- Line 159: should be user_id instead of subscription_id
- Line 165: should be subscription_id instead of user_id
 
Current code
> tokenTypes.user = {
> .....
> .....
>
>            <name>subscription_id</name>
>           <value>
>             <i4>${userID}</i4>
>            </value>
>          </member>${subscriptionID ? `
>          <member>
>            <name>user_id</name>
>            <value>
>             <i4>${subscriptionID}</i4>
>            </value>
>          </member>` : ''}

**Comment by gear54rus** [comment]
Thanks, will look and include the fix if any in the next update.

**Comment by AngelDevel** [comment]
Great! Thanks!
